### ISSUE TITLE
Express usage's OutgoingMessage does not have streamID, isSpdy, spdyVersion, push, etc

### ISSUE THREAD

**Issue by NawarA** [indutny/node-spdy#185]
It looks like non-HTTPS has no SPDY options.

```javascript
    // Regular node http module is used as a base class:
    options = {
        ssl: false,
        plain: true
    };
```
...will produce no SPDY options in the response object. 

Is there anyway to configure node-spdy in the options object to get SPDY options, while ssl = false ?

**Comment by indutny** [comment]
Is it still the case?

**Comment by NawarA** [comment]
Used to be. I switched off Express and use pure Node API, so not sure if this still holds for a server using the express framework. Maybe we close unless we hear its still the case?

**Comment by indutny** [comment]
I think it should be fine now, thanks for reply!
