### ISSUE TITLE
Node 0.12 error

### ISSUE THREAD

**Issue by hanspeter1** [indutny/node-spdy#190]
Spdy 1.30.0/1.30.1 doesn’t work with Node.js 0.12.
I get on express 4.11.2 "express:router dispatching null" and in the Browser "Cannot null".

On Spdy 1.29.2 everything works normal.

**Comment by indutny** [comment]
@hanspeter1 may I ask you to put a test case in a gist and paste it here?

**Comment by albertorestifo** [comment]
Same problem here, there are no errors, every request replies with this:

"Cannot null"

So, it can't even null *badum tsss*

**Comment by goloroden** [comment]
+1

**Comment by indutny** [comment]
Fixed, thanks!
