### ISSUE TITLE
Future of this module with respect to HTTP/2?

### ISSUE THREAD

**Issue by goloroden** [indutny/node-spdy#191]
First of all: I *highly* appreciate this module and use it in several projects :-)

So, please don't get this question wrong: It's not meant to be harshly or impolite, it just came to my mind this evening.

Today, the Chromium project has announced to [drop support for SPDY in early 2016](http://blog.chromium.org/2015/02/hello-http2-goodbye-spdy-http-is_9.html), as HTTP/2 will then be mature enough.

So, I wondered, what does this mean for this module? Will it evolve into an HTTP/2 module over time? Will it get additional support? Will it stay a pure SPDY module? Does it work already for HTTP/2 as well? …?

As said before: Please don't get this question wrong, I really value your work on this module, and I definitely don't want to bash it.

**Comment by indutny** [comment]
This really depends on https://github.com/iojs/io.js/issues/589 and https://github.com/iojs/io.js/issues/4 . First one is required because of ALPN that is used for advertising HTTP2 support. The second one will tell where this module would live.

I think it'll be either support here, on in core.

**Comment by goloroden** [comment]
Thanks for the very fast reply, and for clarifying things :-)
