### ISSUE TITLE
How to get streamID from pushed streams?

### ISSUE THREAD

**Issue by gujason721** [indutny/node-spdy#192]
In a node-spdy client, how can I get the streamID from pushed streams?

agent.on('push', function(stream) {
}

I tried streamID stated in the readme, which doesn't work (console.log('stream id is %s',stream.streamID);). 

Also when printing out the whole stream object, in _spdyState, I can see the field for id, and associated id, and I'm wondering what's the proper method for extracting these information?

**Comment by indutny** [comment]
Sorry, there is no API for this, and now this information is even deeper in the internals!
