### ISSUE TITLE
server push trough nginx reverse proxy

### ISSUE THREAD

**Issue by hdf** [indutny/node-spdy#203]
As it says on the tin. I have successfully gotten my project to use server push, now I would like for this functionality to work trough an nginx reverse proxy. The problem is, that the `response` object doesn't have a `push` property if connecting trough nginx. Is it supposed to be like that? Am I asking for the impossible?

**Comment by hdf** [comment]
I may have an idea, why this is. Nginx connects to the upstream server trough http 1.0 SSL not SPDY, so this is an nginx issue.

**Comment by motss** [comment]
No workaround?

**Comment by hdf** [comment]
nginx developer (Maxim Dounin) confirms, that there are no plans for nginx to support upstream http2:
https://www.ruby-forum.com/topic/6873270#1170325
So the only "workaround" I see, is not to use nginx, if you want Server Push on your node app.

**Comment by motss** [comment]
:+1: Thank you for the source.
