### ISSUE TITLE
spdy custom agent does not work with nock

### ISSUE THREAD

**Issue by goloroden** [indutny/node-spdy#211]
I don't know whether the problem is nock or spdy (or both), hence I'm adding it as an issue here, too: Basically, my problem is that nock works unless I use a custom agent created using spdy module.

The details, including a test case to reproduce the issue can be found here: https://github.com/pgte/nock/issues/356

**Comment by goloroden** [comment]
Okay … I found the issue: Instead of

```javascript
var agent = spdy.createAgent({
  host: 'localhost',
  port: 3000
});
```

it should be:

```javascript
var agent = spdy.createAgent({
  host: 'localhost',
  port: 3000
}).once('error', function (err) {
  this.emit(err);
});
```

Then everything works as expected. Maybe it could be an idea to add this as a hint to the documentation?

**Comment by indutny** [comment]
@goloroden nice! I'm up for changes to the readme. Are you interested in sending a PR?

**Comment by goloroden** [comment]
I'll come up with one :-)

Just give me a little time…

**Comment by goloroden** [comment]
I've sent a PR.

The build fails, but since I only updated the `README.md` file I guess the build already failed before ;-)

**Comment by indutny** [comment]
Thank you!

**Comment by goloroden** [comment]
You're welcome :-)

Since [things are documented now](https://github.com/indutny/node-spdy/tree/e731db81065546d5c2bccb0832ff6c4d9987d4e4), I'm closing this issue :-)
