### ISSUE TITLE
io.js 4 compatibility

### ISSUE THREAD

**Issue by ronkorving** [indutny/node-spdy#220]
Hi @indutny,

As you pointed out in https://github.com/nodejs/node/pull/2355#issuecomment-130160260, node-spdy will soon no longer be compatible with io.js (v4 that is). What's the plan forward? Does this mean trouble or are there ways to work with the new challenges?

**Comment by indutny** [comment]
Actually, I was very wrong. Tests are passing for me :) Please let me know if they are not passing for you.

**Comment by ronkorving** [comment]
Ah nice :) Really glad to hear that. :+1:
