### ISSUE TITLE
WebSocket compatibility

### ISSUE THREAD

**Issue by ronkorving** [indutny/node-spdy#224]
Right now, when I use https://www.npmjs.com/package/ws on top of a node-spdy server, the following happens:

```
  spdy:server incoming socket protocol="http/1.1" +8s
  spdy:server to default handler it goes +0ms
  spdy:server incoming socket protocol="http/1.1" +12ms
  spdy:server to default handler it goes +0ms
```

This might just be Chrome not using the existing HTTP/2 connection that has already been established, or it might be Chrome not supporting WebSocket over HTTP/2. I'm making this issue just in case it may be node-spdy not supporting the protocol upgrade.

Does anyone have any deeper insights on this?

**Comment by indutny** [comment]
I don't think that http2 is used when establishing websocket connection.

**Comment by ronkorving** [comment]
Ever? I remember seeing an RFC about this very topic. Not sure about its status though.

**Comment by tatsuhiro-t** [comment]
IIRC, there was effort to make WebSocket connection over HTTP/2, but there was no consensus about how to achieve it.  I'm not sure it is still ongoing.  I think all browsers today use HTTP/1.1 connection for WebSocket.

**Comment by ronkorving** [comment]
Reference: http://tools.ietf.org/html/draft-hirano-httpbis-websocket-over-http2-00 (may be expired, rejected, I don't know)
