### ISSUE TITLE
getCounter() function not found on connection object

### ISSUE THREAD

**Issue by anandsuresh** [indutny/node-spdy#225]
Line no. 271 on push_stream.js throws an error about the getCounter() function not being present on the connection object.

**Comment by indutny** [comment]
@anandsuresh I have fixed counters, I suggest to use `req.socket.getCounter('push')` at `push_stream.js`.

**Comment by indutny** [comment]
@anandsuresh actually, I was wrong `req.socket._handle.stream.connection.getCounter`. Sorry, it is too deep!
