### ISSUE TITLE
ERR_SPDY_INADEQUATE_TRANSPORT_SECURITY

### ISSUE THREAD

**Issue by rpavez** [indutny/node-spdy#231]
I tried this module today with a self-signed certificate but got this error when running in my local machine, any idea how to fix it?
![screen shot 2015-11-06 at 11 11 27 am](https://cloud.githubusercontent.com/assets/555910/10998882/2ffbfa38-8477-11e5-8d9f-50819d46a295.png)

**Comment by indutny** [comment]
To be able to run HTTP2 server you need a web server that:

* Provides TLS 1.2
* It should support (and select) SSL ciphers with ECDHE/DHE key exchange and AES-128-GCM/AES-256-GCM/CHA-CHA encryption

Pretty sure that either of these requirements were not fulfilled.
