### ISSUE TITLE
Response object does not have push function

### ISSUE THREAD

**Issue by motss** [indutny/node-spdy#236]
I have been facing an error saying that `push` is not a function of the `response` object when the module tries to push some files from Node Server through Nginx reverse proxy.

**Comment by indutny** [comment]
Hello!

Is `request.isSpdy` `true`?

Thank you,
Fedor.

**Comment by motss** [comment]
IKR. It's `false`.

**Comment by indutny** [comment]
If it is `false` - your server is receiving regular HTTP/1.1 request, not a SPDY request. There is no PUSH streams in HTTP/1.1 specification, so there is no PUSH support for this requests too.

To be able to PUSH stuff, you need to establish HTTP/2 or SPDY connection between nginx and node-spdy, and I have no idea how to do it, or if it is possible to do. Sorry!

**Comment by motss** [comment]
Okay, I just hope for native support from Nginx.
