### ISSUE TITLE
Protocol error on push promise

### ISSUE THREAD

**Issue by tresdin** [indutny/node-spdy#237]
I got the protocol error while I was trying to push multiple files via `PUSH_PROMISE`. Here is the sample code.
```
spdy.createServer(options, function(req, res) {
	['/app/main.js','/app/main.css','/app/favicon-32x32.png'].forEach(function(url){
		console.log('fetching',url);
	  var stream = res.push(url, {
		  'content-type': `${MIME[url.substr(url.lastIndexOf('.')+1)]};charset=utf-8`,
		  'content-encoding' : 'gzip',
		});
	  stream.on('error', function(er) {
		  throw er;
	  });
	  var fstream = fs.createReadStream('/home'+url);
	  fstream.pipe(stream);
	});
  

  res.end(`
	<!DOCTYPE html>
	<html>
		<head>
			<script src="/app/main.js" async></script>
			<link rel="stylesheet" href="/app/main.css" async>
			<link rel="icon" type="image/png" href="/app/favicon-32x32.png" sizes="32x32" async>
			<meta name="viewport" content="width=device-width, initial-scale=1">
		</head>
		<body></body>
	</html>`
  );
```
Result:
![untitled](https://cloud.githubusercontent.com/assets/7781091/11977359/71506264-a9b4-11e5-9b8e-f54bea0c44da.png)

Anything wrong with my code? Or is this a `node-spdy` bug?

**Comment by indutny** [comment]
@tresdin may I ask you to provide `npm ls spdy` output here?

**Comment by tresdin** [comment]
@indutny No problem.
![untitled2](https://cloud.githubusercontent.com/assets/7781091/11979823/f74a8764-a9c8-11e5-86b5-96d9ddf2c166.png)
That's all I have.

**Comment by indutny** [comment]
@tresdin thank you! May I ask you to also run `npm ls spdy-transport`?

**Comment by tresdin** [comment]
@indutny Here you are.
![untitled3](https://cloud.githubusercontent.com/assets/7781091/11979936/c6419d6e-a9c9-11e5-998c-02de3f3d3811.png)

**Comment by indutny** [comment]
Thank you! Two more question to you:

1. What browser are you using to test it? Does it fail in other browser too?
2. Could you please run the same scenario with `DEBUG="spdy*"` environment variable and upload the output log to gist.github.com ?

Thank you again!

**Comment by tresdin** [comment]
@indutny 
1. I tested on `Chrome Version 47.0.2526.106 m (64-bit)`. Here is the result on Firefox. 

![untitled-firefox](https://cloud.githubusercontent.com/assets/7781091/11989137/ed5d9496-aa2a-11e5-873a-eeb2f0fa22d5.png)
2. Could you point me out the location of log file? I've tested with `node /home/app/index.js DEBUG="spdy*"` but nothing else happened.

**Comment by indutny** [comment]
@tresdin you will need to run it like this `DEBUG="spdy*" node /home/app/index.js`. Thanks for testing it on Firefox.

**Comment by tresdin** [comment]
@indutny My output log https://gist.github.com/tresdin/908a0ebf0ea67a9c9783

**Comment by tresdin** [comment]
@indutny Sorry for the wrong log. Here is the one with this error. https://gist.github.com/tresdin/e557984ceba774853e3e

**Comment by indutny** [comment]
Thank you very much for detailed logs. However, I'm afraid I still need a bit more information than this.

May I ask you to open `chrome://net-internals/#export` in Chrome before testing it (please make sure that you do not have any other tabs open so that they won't leak any private data), start the server, reproduce the issue, and click "Save to file" there in chrome. You may want to send the output log by email, just in case if it contains any private data (I will make sure nothing will be exposed).

Thank you again!

**Comment by indutny** [comment]
Nevermind, I know what is happening. Will create a fix today.

**Comment by indutny** [comment]
Ah, actually I was wrong. I still need that `net-internals` log. Sorry!

**Comment by tresdin** [comment]
@indutny I've sent the log to *fedor@indutny.com*.

**Comment by indutny** [comment]
@tresdin thank you! So the answer for our problem is:

```
Received duplicate pushed stream with url: https://hostname/app/favicon-32x32.png
```

I think if you will handle `err` instead of re-throwing it in `error` event listener - you should be able to handle it. It doesn't look like a problem on node-spdy side.

The idea behind this error message is that you actually push streams on every incoming request, and this error happens if you push the same url twice on the same TLS connection.

Thank you very much for providing the log.

**Comment by tresdin** [comment]
@indutny 
> The idea behind this error message is that you actually push streams on every incoming request

This error still stands when requests are filtered.
```
if(req.url === '/'){
    ['/app/main.js','/app/main.css','/app/favicon-32x32.png'].forEach(function(url){
        console.log('fetching',url);
      var stream = res.push(url, {
          'content-type': `${MIME[url.substr(url.lastIndexOf('.')+1)]};charset=utf-8`,
          'content-encoding' : 'gzip',
        });
      stream.on('error', function(er) {
          throw er;
      });
      var fstream = fs.createReadStream('/home'+url);
      fstream.pipe(stream);
    });


  res.end(`
    <!DOCTYPE html>
    <html>
        <head>
            <script src="/app/main.js" async></script>
            <link rel="stylesheet" href="/app/main.css" async>
            <link rel="icon" type="image/png" href="/app/favicon-32x32.png" sizes="32x32" async>
            <meta name="viewport" content="width=device-width, initial-scale=1">
        </head>
        <body></body>
    </html>`
  );
}
```
> this error happens if you push the same url twice on the same TLS connection

How can url be pushed twice on the same TLS connection with my sample code? And also, what is your  solution for this error?

**Comment by indutny** [comment]
@tresdin the browser may cancel any PUSH stream if it thinks that it needs to do so (be it duplicate streams, or whatever). The solution is to handle `error` event on PUSH stream, and act accordingly.

**Comment by tresdin** [comment]
@indutny I just want to know the cause of the duplication. You've confirmed that this error is not from node spdy side. So which part of my code causes this error? Or is this a Chrome bug?

**Comment by indutny** [comment]
@tresdin this is not a bug at all. Browser just decides that it does not want to receive any data from that PUSH stream and cancels it. This is completely legal in HTTP2

**Comment by tresdin** [comment]
@indutny I think it should be considered as a bug. Browsers assume that this behaviour is incorrect on server side when some duplicated streams are sent. So the problem can only be solved when browsers stop rejecting incoming pushed streams.

**Comment by indutny** [comment]
@tresdin I don't get why it is a bug. Please remove `throw err` from your code, and it will work just fine.
