### ISSUE TITLE
certs required?

### ISSUE THREAD

**Issue by mitchellsimoens** [indutny/node-spdy#255]
Are the `key`, `cert` and `ca` configs required? In production I use AWS Elastic Beanstalk which handles the cert stuff so in my node app I do not have access to them (or need to have access to it) but I'm getting a 502 Bad Gateway while it works locally where I have a self-signed cert. Tried passing the `ssl` config but that made no difference either.

**Comment by indutny** [comment]
Hello!

If I understood it right - you are running a node-spdy server behind an AWS TLS balancer. If this is the case - I would suggest using `plain: true, ssl: false` options.

Hopefully it will help,
Fedor.

**Comment by mitchellsimoens** [comment]
Sorry, meant to close this. The real issue here, and sorry for spamming your issues, is that AWS EB doesn't support http/2 yet.
