### ISSUE TITLE
process.EventEmitter is deprecated!

### ISSUE THREAD

**Issue by NKITMedia** [indutny/node-spdy#257]
Just to let you know:

process.EventEmitter is deprecated as of Node version 6.1.0

```javascript
function Connection(socket, options, server) {
  process.EventEmitter.call(this);
```

(node:6048) DeprecationWarning: process.EventEmitter is deprecated. Use require('events') instead.

**Comment by indutny** [comment]
Thank you! It really looks like you are using the old version of node-spdy, though. So I'm not sure if it is going to be fixed.
