### ISSUE TITLE
Listen http and https to the same port

### ISSUE THREAD

**Issue by buzinas** [indutny/node-spdy#261]
I found some examples over the internet, but none of them are simple, nor they can handle redirecting - for example - http://localhost:3000/ to https://localhost:3000/

I found one to redirect the default ports 80 to 443, but those ones don't apply for the app I'm building, unfortunately. And I don't want to have any reverse proxy webserver in front of Node.js also.

So, being direct: is there any simple way to redirect all the http requests to https?

**Comment by indutny** [comment]
Sorry, but I don't think that this mode is going to be supported in node-spdy.

You may give a try to [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security).
