### ISSUE TITLE
isSpdy and spdyVersion are not set for res/OutgoingMessage

### ISSUE THREAD

**Issue by webcarrot** [indutny/node-spdy#267]
[README](/indutny/node-spdy/blob/master/README.md):

> Request listener will receive two arguments: request and response. They're both instances of http's IncomingMessage and OutgoingMessage. But three custom properties are added to **both** of them: isSpdy, spdyVersion.

witch is not true... [line 229](/indutny/node-spdy/blob/master/lib/spdy/server.js#L229)

**Comment by indutny** [comment]
Yikes! This is definitely a bug. Does filing a PR to fix sound interesting you?

Thanks!

**Comment by webcarrot** [comment]
This is bug in code ... or in documentation - not my project and not my decision how to fix it.

**Comment by indutny** [comment]
Ah, that's right! Sorry to not mention it. I believe this is a bug in the code, not in the docs.

Please do not hesitate to ask me if you need any pointers or tips, I'll be more than happy to help!
