### ISSUE TITLE
spdy vs. http/2

### ISSUE THREAD

**Issue by azat-co** [indutny/node-spdy#269]
this is more of a question. i kept hearing spdy is [dead](https://github.com/molnarg/node-http2/issues/100#issuecomment-238672259) but I think people refer to the protocol not this library

when I'm using this package, Chrome identifies it as http/2 or h2 which what I need

could you please clarify if you are planning to support http/2? if it's supports http/2? if you just left the name from spdy protocol but basically this is an h2 lib?

**Comment by indutny** [comment]
Hello!

Despite very confusing name, this package provides support for both http/2 (h2) and spdy (2,3,3.1).

**Comment by azat-co** [comment]
@indutny great! great! great! that's what I thought.

I wrote two blog posts about spdy and express (third is coming), so it's good to know this is the module to use for node and H2.

FYI,

https://github.com/azat-co/nc-posts/blob/master/http2-node-server-push.md

http://webapplog.com/http2-node/

**Comment by indutny** [comment]
Lovely! Thank you!
