### ISSUE TITLE
Rename the package and clean it out?

### ISSUE THREAD

**Issue by bonesoul** [indutny/node-spdy#273]
So as spdy protocol is officially dead now how about cleaning this module to only support http2?

**Comment by indutny** [comment]
There are still some services that need SPDY, so it is unlikely that it is going away very soon from this repo.

Regarding the name, what name do you propose?

**Comment by bonesoul** [comment]
node-http2 ?

is there a way to disable SPDY support right now while running the package?

**Comment by indutny** [comment]
Yep, there is `protocols` option: https://github.com/indutny/node-spdy#usage

**Comment by bonesoul** [comment]
okay for future reference the folowing was what i needed;

```
  protocols: [ 'h2', 'http/1.1' ], // enable http2 and http/1.1 for fallback.
```
