### ISSUE TITLE
H2 Problem with new Chrome

### ISSUE THREAD

**Issue by umutgumeli** [indutny/node-spdy#275]
I just updated Chrome and my sites not loading with H2 (requests are cancelling by browser). SPDY 3.1 looks fine.
Chrome Version 54.0.2840.27 beta

**Comment by atakangktepe** [comment]
+1

**Comment by apapirovski** [comment]
Just do "npm install spdy" again. There are new versions of [indutny/spdy-transport](https://github.com/indutny/spdy-transport) & [indutny/hpack.js](https://github.com/indutny/hpack.js) that deal with this. See https://github.com/indutny/spdy-transport/issues/29

That said, maybe this is a big enough deal that a new version of `node-spdy` should be released with the dependency version bumped? I realize it's technically not necessary but this will leave a lot of sites stranded once that version of Chrome actually goes public.

**Comment by umutgumeli** [comment]
It works! Thanks bro 🎉
I think we must see new updates for modules we are using like app stores. Hope other sites using node-spdy update soon

**Comment by indutny** [comment]
Pushed out spdy@3.4.2 with updated `spdy-transport` dependency.

Thanks everyone!
