### ISSUE TITLE
`res.finished` doesn't work when using h2 protocol

### ISSUE THREAD

**Issue by SpaceK33z** [indutny/node-spdy#276]
I've found an interesting issue. When using the `h2` protocol, `res.finished` always returns `false`. Using `http/1.1` as a protocol, this does work correctly.

Some sample code to reproduce:

```js
var options = {
	spdy: {
		protocols: ['h2'],
		// Replace with this to see correct value:
		// protocols: ['http/1.1'],
	},
};

var server = spdy.createServer(options, function(req, res) {
	res.writeHead(200);
	res.end('hello world!');
	console.log('res finished:', res.finished);
});

server.listen(8080);
```

In this example, I would expect that the console outputs: `res finished: true`.

I wanted to try spdy with the `sockjs-node` package, but that doesn't work because of this issue. Took me a few hours to discover the root cause :).

Also see [Node.js documentation](https://nodejs.org/api/http.html#http_response_finished) about this.

**Comment by indutny** [comment]
Fixed, sorry!

**Comment by SpaceK33z** [comment]
Wow thanks for the quick fix!
