### ISSUE TITLE
`spdy.maxStreams` unused?

### ISSUE THREAD

**Issue by tony19** [indutny/node-spdy#286]
The README indicates an option to set max concurrent streams for server-push:

> `maxStreams` - set "maximum concurrent streams" protocol option

But I found no reference to this option in the current code. It looks like it was actually removed in fa1e8cd (as part of #34). Are there plans to re-implement the option? Or is the option permanently removed (and the README out of date)?

**Comment by anandsuresh** [comment]
@tony19 The refactor you're referring to was made to modularize the code-base. All SPDY transport-specified code was moved into the `spdy-transport` npm module, which still supports the `maxStreams` option [here](https://github.com/indutny/spdy-transport/blob/master/lib/spdy-transport/connection.js#L41-L42).

Hope this helps.

**Comment by tony19** [comment]
@anandsuresh Ah, yes. Thanks!
