### ISSUE TITLE
Priotirization support

### ISSUE THREAD

**Issue by Cactucs** [indutny/node-spdy#296]
It seems that there is no prioritisation support. 

It should respect browser-defined stream priority (as defined in section 5.3 of HTTP/2 specs) as well as support specifying priority when pushing resources.

(I haven't found any indication of implementation of this.)

See: 
http://httpwg.org/specs/rfc7540.html#StreamPriority
https://nghttp2.org/blog/2014/04/27/how-dependency-based-prioritization-works/

**Comment by indutny** [comment]
It actually works, but on the level of spdy-transport: https://github.com/indutny/spdy-transport/blob/master/lib/spdy-transport/priority.js .

**Comment by Cactucs** [comment]
Am I able / how to set pushed resources weight in dependency tree? And set
other requests' dependency tree.

**Comment by worenga** [comment]
> Am I able / how to set pushed resources weight in dependency tree?
> And set other requests' dependency tree?

I would really be interested in that as well. It seems pushed objects are interleaved with the main response. Any idea how to avoid this?
