### ISSUE TITLE
Windows npm install throws error on spdy

### ISSUE THREAD

**Issue by Pfannkuchensack** [indutny/node-spdy#297]
204 http request GET https://registry.npmjs.org/spdy
205 info git [ 'config', '--get', 'remote.origin.url' ]
206 verbose stack Error: spawn UNKNOWN
206 verbose stack     at exports._errnoException (util.js:870:11)
206 verbose stack     at ChildProcess.spawn (internal/child_process.js:298:11)
206 verbose stack     at exports.spawn (child_process.js:362:9)
206 verbose stack     at exports.execFile (child_process.js:151:15)
206 verbose stack     at execGit (C:\nodejs\node_modules\npm\lib\utils\git.js:23:10)
206 verbose stack     at C:\nodejs\node_modules\npm\lib\utils\git.js:49:5
206 verbose stack     at C:\nodejs\node_modules\npm\node_modules\which\which.js:89:20
206 verbose stack     at C:\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
206 verbose stack     at C:\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
206 verbose stack     at FSReqWrap.oncomplete (fs.js:82:15)

i cant run npm install on windows if any dependencies have spdy as dependencie.

**Comment by indutny** [comment]
I'm afraid it is unrelated to this module all in all. This error says that you don't have `git` either installed or in PATH on that machine.

Hope this helps!

**Comment by Pfannkuchensack** [comment]
i can start git from my cmd.
i run the install on a linux maschine and copy it to my windows.
